spring:
  datasource:
    url: jdbc:h2:file:./data/licadb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

sso:
  issuer: https://sso.example.com
  key:
    private-key-path: ./data/keys/private.pem
    public-key-path: ./data/keys/public.pem
    kid: lica-prod-key-1
